import math
import torch
import torch.nn as nn
from torch.nn.functional import cosine_similarity

def get_collapse_level(p1):
    """
    表征方差越小，塌缩越显著
    为证明退化是由坍缩引起的，我们研究
    了ℓ2归一化输出z/ z 2的标准差（std）。若输出坍缩
    为恒定向量，则所有样本在各通道上的std应趋近于零
    。这一现象可从图2（中）的红色曲线中观察到。
    作为对比，若输出z服从零均值各向同性高斯分布，
    我们可以证明z/ z 2的标准差为1 / √d 。
    """
    # calculate the per-dimension standard deviation of the outputs
    # we can use this later to check whether the embeddings are collapsing
    output = p1.detach()
    
    with torch.autocast(device_type='cuda', enabled=False):
        output = torch.nn.functional.normalize(output.float(), dim=-1)
        output_std = torch.std(output, 0)
    output_std = output_std.mean().cpu().item() * math.sqrt(p1.shape[-1])
    
    # # the level of collapse is large if the standard deviation of the l2
    # # normalized output is much smaller than 1 / sqrt(dim)
    # collapse_level = max(0.0, 1 - math.sqrt(out_dim) * avg_output_std)
    return output_std

class NegativeCosineSimilarity(torch.nn.Module):

    def __init__(self, dim: int = -1, eps: float = 1e-8) -> None:
        super().__init__()
        self.dim = dim
        self.eps = eps

    def forward(self, x0, x1):
        with torch.autocast(device_type='cuda', enabled=False):
            loss = 1 - cosine_similarity(x0.float(), x1.float(), self.dim, self.eps).mean()
        return loss
    
def deactivate_requires_grad(model: nn.Module):
    """Deactivates the requires_grad flag for all parameters of a model.

    This has the same effect as permanently executing the model within a `torch.no_grad()`
    context. Use this method to disable gradient computation and therefore
    training for a model.

    Examples:
        >>> backbone = resnet18()
        >>> deactivate_requires_grad(backbone)
    """
    for param in model.parameters():
        param.requires_grad = False


@torch.no_grad()
def update_momentum(model, model_ema, m):
    """Updates parameters of `model_ema` with Exponential Moving Average of `model`

    Momentum encoders are a crucial component for models such as MoCo or BYOL.

    Args:
        model:
            The current model.
        model_ema:
            The model with exponential moving average (EMA) parameters.
        m:
            The momentum factor, between 0 and 1.

    Examples:
        >>> backbone = resnet18()
        >>> projection_head = MoCoProjectionHead()
        >>> backbone_momentum = copy.deepcopy(moco)
        >>> projection_head_momentum = copy.deepcopy(projection_head)
        >>>
        >>> # update momentum
        >>> update_momentum(moco, moco_momentum, m=0.999)
        >>> update_momentum(projection_head, projection_head_momentum, m=0.999)
    """
    for model_ema, model in zip(model_ema.parameters(), model.parameters()):
        # model_ema.data = model_ema.data * m + model.data * (1.0 - m)
        model_ema.data.mul_(m).add_((1.0-m) * model.detach().data)

def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor

def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (Tensor, float, float, float, float) -> Tensor
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)


class LinearWithConstraint(nn.Linear):
    def __init__(self, *args, doWeightNorm = True, max_norm=1, **kwargs):
        self.max_norm = max_norm
        self.doWeightNorm = doWeightNorm
        super(LinearWithConstraint, self).__init__(*args, **kwargs)

    def forward(self, x):
        if self.doWeightNorm: 
            self.weight.data = torch.renorm(
                self.weight.data, p=2, dim=0, maxnorm=self.max_norm
            )
        return super(LinearWithConstraint, self).forward(x)

def __gen_mask__(group, num_pad=0, pad_offset=0):
    Expand   = group.unsqueeze(1)
    Expand_T = group.unsqueeze(2)
    mask     = (Expand == Expand_T)
    B, S, _  = mask.shape
    if num_pad>0:
        pad = torch.ones(
                    (B, S+num_pad, S+num_pad), 
                    dtype=mask.dtype, 
                    device=mask.device)
        pad[:, :S, :S] = mask
        pad[:, :pad_offset, S:] = 0
        pad[:, S:, :pad_offset] = 0
        mask = pad
    return mask # [B, S+, S+]
    
def generate_attention_mask(
                            chan_pos, 
                            time_pos, 
                            chan_pos_sum, 
                            time_pos_sum,
                            embed_num,
                            num_heads,
                            num_heads_chan=None,
                            num_heads_time=None,
                            use_all_attn=False,
                            use_indp_chan_sum=False,
                            use_indp_time_sum=False,
                            ):
    """
    : chan_pos long [B, N] start from 1
    : time_pos long [B, N] start from 1
    : chan_pos_sum long [B, N] start from 1
    : time_pos_sum long [B, N] start from 1
    : embed_num tuple (chan, time, both)
    """
    if chan_pos is None:
        B, N  =time_pos.shape
        dtype =time_pos.dtype
        device=time_pos.device
    else:
        B, N  =chan_pos.shape
        dtype =chan_pos.dtype
        device=chan_pos.device
    
    if use_all_attn:
        return None
        # # [B, N+(CS*EN0)+(TS*EN1)+EN2,]
        # mask_size = N + ((0 if chan_pos_sum is None else chan_pos_sum.shape[1])*embed_num[0]) + \
        #                 ((0 if time_pos_sum is None else time_pos_sum.shape[1])*embed_num[1]) + embed_num[2]
        # # attn_mask = torch.ones_like(attn_mask).bool()
        
        # attn_mask = torch.ones((B, num_heads, mask_size, mask_size)).\
        #                   to(dtype=dtype,device=device)
        # return attn_mask
    
    if num_heads_chan is None:
        num_heads_chan = num_heads//2
    if num_heads_time is None:
        num_heads_time = num_heads - num_heads_chan
    
    attn_mask_heads = []
    
    if num_heads_chan>0:
        chan_pos_sum = torch.repeat_interleave(chan_pos_sum, repeats=embed_num[0], dim=1)
        if use_indp_chan_sum:
            chan_neg_sum = -torch.arange(1,chan_pos_sum.shape[1]+1).unsqueeze_(0).repeat((B,1)).\
                to(dtype=chan_pos_sum.dtype, device=chan_pos_sum.device) // (embed_num[0])
        else:
            chan_neg_sum = -torch.ones_like(chan_pos_sum)
        
    if num_heads_time>0:
        time_pos_sum = torch.repeat_interleave(time_pos_sum, repeats=embed_num[1], dim=1)
        if use_indp_time_sum:
            time_neg_sum = -torch.arange(1,time_pos_sum.shape[1]+1).unsqueeze_(0).repeat((B,1)).\
                to(dtype=time_pos_sum.dtype, device=time_pos_sum.device) // (embed_num[1])
        else:
            time_neg_sum = -torch.ones_like(time_pos_sum)
        
    if num_heads_chan>0:
        attn_mask_chan = torch.cat([chan_pos, chan_pos_sum] + 
                                  ([time_neg_sum] if num_heads_time>0 else []), dim=1) 
        attn_mask_chan = __gen_mask__(attn_mask_chan, embed_num[2], N)
        attn_mask_heads.append(attn_mask_chan.unsqueeze_(1).repeat((1,num_heads_chan,1,1)))
    
    if num_heads_time>0:
        attn_mask_time = torch.cat([time_pos] + 
                                  ([chan_neg_sum] if num_heads_chan>0 else []) + [time_pos_sum], dim=1) 
        attn_mask_time = __gen_mask__(attn_mask_time, embed_num[2], N)
        attn_mask_heads.append(attn_mask_time.unsqueeze_(1).repeat((1,num_heads_time,1,1)))
    
    attn_mask = torch.cat(attn_mask_heads, dim=1)
    return attn_mask # [B, num_heads, T, T]



def visualize_mask(mask_tensor):
    """
    可视化attention mask矩阵
    参数:
        mask_tensor: 字符串形式的PyTorch张量表示
    返回:
        可视化后的字符串
    """
    # 从字符串中提取矩阵数据
    rows = []
    for line in mask_tensor.split('\n'):
        if '[' in line:
            # 移除行首尾的空白和括号
            clean_line = line.strip()[1:-1]
            # 分割数字
            if clean_line:
                row = [int(x.strip()) for x in clean_line.split(',') if x.strip()]
                rows.append(row)
    
    # 创建可视化字符串
    visual = []
    for row in rows:
        # 将1转换为■，0转换为空格
        visual_row = ''.join('■' if bit == 1 else ' ' for bit in row)
        visual.append(visual_row)
    
    return '\n'.join(visual)

def visualize_tensor(mask_tensor):
    return '\n'.join(''.join('■, ' if x else '_, ' for x in row) 
                    for row in mask_tensor.cpu().numpy())