ckpt_path: logs_EEGPT_mcae/checkpoints/last-EEGPT_mcae_CAE_d8_e256_444_A000000_q0th0t0f0a1c0i0o2siam1s2025-ep199-vs1.2880.ckpt
seed: 2026
version: d8_e256_444_A000000_q0th0t0f0a1c0i0o2siam1s2026
KEY: EEGPT_mcae
SKEY: CAE
max_epochs: 200
steps_per_epoch: 214
max_lr: 0.0005
batch_size: 320
early_stop: 5
log_path: ./logs_EEGPT_mcae/
log_name: EEGPT_mcae_CAE
save_path: ./logs_EEGPT_mcae/checkpoints
save_name: EEGPT_mcae_CAE_d8_e256_444_A000000_q0th0t0f0a1c0i0o2siam1s2026-ep{epoch}-vs{valid_loss:.4f}
use_IdentityAE: false
devices:
- 0
- 1
- 2
- 3
- 4
weight_loss_a: 1.0
num_workers: 20
percentile_q: -1
use_tanh: false
use_tiny_data: false
use_fake_data: false
patch_size: 50
output_num: 2
embed_dim: 256
embed_num:
- 4
- 4
- 4
depth: 8
num_heads: 16
mNCxy:
- 7
- 13
- 7
- 13
use_avg_ref: true
enc_use_all_attn: false
enc_use_indp_chan_sum: false
enc_use_indp_time_sum: false
dec_use_all_attn: false
dec_use_indp_chan_sum: false
dec_use_indp_time_sum: false
use_time_indp_attn: true
use_siamese_forward: true
predictor_embed_dim: 128
predictor_embed_dim_inp: 256
predictor_depth: 8
use_predictor: true
use_combine_z: true
train_phase: true
valid_phase: false
use_compile: false
test: true
